# Generated by Django 3.0 on 2023-11-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished', models.IntegerField(default=0)),
                ('allPoints', models.IntegerField(default=0)),
            ],
        ),
    ]
